version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tudorsaitoc"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      nextjs:
        patterns:
          - "next"
          - "eslint-config-next"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"

  # Backend dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tudorsaitoc"
    labels:
      - "dependencies"
      - "backend"
    groups:
      langchain:
        patterns:
          - "langchain*"
      fastapi:
        patterns:
          - "fastapi"
          - "uvicorn*"
          - "pydantic*"
      testing:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "tudorsaitoc"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "tudorsaitoc"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "tudorsaitoc"
    labels:
      - "dependencies"
      - "docker"