#!/bin/bash

echo "🔧 Fix GCP Service Account Permissions"
echo "====================================="
echo ""
echo "Your service account: serviceaccount@validateio.iam.gserviceaccount.com"
echo ""

echo "You need to grant these permissions to your service account:"
echo ""

echo "1️⃣ Go to: https://console.cloud.google.com/iam-admin/iam"
echo ""

echo "2️⃣ Find your service account in the list"
echo "   Look for: serviceaccount@validateio.iam.gserviceaccount.com"
echo ""

echo "3️⃣ Click the pencil icon to edit permissions"
echo ""

echo "4️⃣ Add these roles:"
echo "   ✅ Cloud Run Admin"
echo "   ✅ Service Account User" 
echo "   ✅ Cloud Build Editor"
echo "   ✅ Artifact Registry Administrator"
echo "   ✅ Storage Admin"
echo ""

echo "5️⃣ Alternative: Run these commands in Cloud Shell"
echo ""
echo "PROJECT_ID=validateio"
echo "SERVICE_ACCOUNT=serviceaccount@validateio.iam.gserviceaccount.com"
echo ""
echo "# Grant Cloud Run Admin"
echo "gcloud projects add-iam-policy-binding \$PROJECT_ID \\"
echo "  --member=\"serviceAccount:\$SERVICE_ACCOUNT\" \\"
echo "  --role=\"roles/run.admin\""
echo ""
echo "# Grant Service Account User"
echo "gcloud projects add-iam-policy-binding \$PROJECT_ID \\"
echo "  --member=\"serviceAccount:\$SERVICE_ACCOUNT\" \\"
echo "  --role=\"roles/iam.serviceAccountUser\""
echo ""
echo "# Grant Cloud Build Editor"
echo "gcloud projects add-iam-policy-binding \$PROJECT_ID \\"
echo "  --member=\"serviceAccount:\$SERVICE_ACCOUNT\" \\"
echo "  --role=\"roles/cloudbuild.builds.editor\""
echo ""
echo "# Grant Artifact Registry Admin"
echo "gcloud projects add-iam-policy-binding \$PROJECT_ID \\"
echo "  --member=\"serviceAccount:\$SERVICE_ACCOUNT\" \\"
echo "  --role=\"roles/artifactregistry.admin\""
echo ""
echo "# Grant Storage Admin"
echo "gcloud projects add-iam-policy-binding \$PROJECT_ID \\"
echo "  --member=\"serviceAccount:\$SERVICE_ACCOUNT\" \\"
echo "  --role=\"roles/storage.admin\""
echo ""

echo "6️⃣ Enable Required APIs"
echo ""
echo "Also make sure these APIs are enabled:"
echo "gcloud services enable run.googleapis.com"
echo "gcloud services enable cloudbuild.googleapis.com"
echo "gcloud services enable artifactregistry.googleapis.com"
echo ""

echo "7️⃣ Quick Fix via Console"
echo ""
echo "Easiest way - give broader permissions temporarily:"
echo "1. Go to: https://console.cloud.google.com/iam-admin/iam?project=validateio"
echo "2. Find: serviceaccount@validateio.iam.gserviceaccount.com"
echo "3. Add role: \"Editor\" (broad permissions)"
echo "4. Try deployment again"
echo "5. Later, reduce to specific roles above"