name: Direct Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Deploy Frontend
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: validateio-frontend
        source: ./frontend
        region: us-central1
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        flags: '--allow-unauthenticated --port=3000'
        env_vars: |
          NEXT_PUBLIC_API_URL=https://validateio-backend-847973892251.us-central1.run.app

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Deploy Backend
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: validateio-backend
        source: ./backend
        region: us-central1
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        flags: '--allow-unauthenticated --port=8080 --memory=1Gi'
        env_vars: |
          ENVIRONMENT=production
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}