name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_frontend:
        description: 'Deploy frontend'
        required: false
        default: 'true'
      deploy_backend:
        description: 'Deploy backend'
        required: false
        default: 'true'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend:
            - 'frontend/**'
            - '.github/workflows/deploy.yml'
          backend:
            - 'backend/**'
            - '.github/workflows/deploy.yml'

  deploy-frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch' || github.event.inputs.deploy_frontend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - uses: google-github-actions/setup-gcloud@v2
    
    - name: Build and Deploy Frontend
      working-directory: ./frontend
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        REGION: us-central1
      run: |
        # Build and deploy using Cloud Build
        gcloud builds submit . \
          --tag gcr.io/${PROJECT_ID}/validateio-frontend \
          --timeout=20m
        
        gcloud run deploy validateio-frontend \
          --image gcr.io/${PROJECT_ID}/validateio-frontend \
          --region ${REGION} \
          --allow-unauthenticated \
          --port 3000 \
          --set-env-vars "NEXT_PUBLIC_API_URL=https://validateio-backend-${{ secrets.GCP_PROJECT_NUMBER }}.${REGION}.run.app"

  deploy-backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - uses: google-github-actions/setup-gcloud@v2
    
    - name: Build and Deploy Backend
      working-directory: ./backend
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        REGION: us-central1
      run: |
        # Build and deploy using Cloud Build
        gcloud builds submit . \
          --tag gcr.io/${PROJECT_ID}/validateio-backend \
          --timeout=20m
        
        gcloud run deploy validateio-backend \
          --image gcr.io/${PROJECT_ID}/validateio-backend \
          --region ${REGION} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --set-env-vars "ENVIRONMENT=production" \
          --set-env-vars "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
          --set-env-vars "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" \
          --set-env-vars "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" \
          --set-env-vars "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
          --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}"