name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches: [ test-secrets ]

jobs:
  test-secrets:
    name: Test Secret Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test Required Secrets
      run: |
        echo "🔍 Testing GitHub Secrets Configuration"
        echo "======================================"
        echo ""
        
        # Function to check if secret exists
        check_secret() {
          local name=$1
          local value=$2
          if [ -z "$value" ]; then
            echo "❌ $name: NOT SET"
            return 1
          else
            # Show partial value for verification (first 4 chars only)
            if [ ${#value} -gt 4 ]; then
              echo "✅ $name: SET (starts with: ${value:0:4}...)"
            else
              echo "✅ $name: SET"
            fi
            return 0
          fi
        }
        
        # Track missing secrets
        MISSING_SECRETS=0
        
        echo "1️⃣ Core Secrets:"
        check_secret "GCP_PROJECT_ID" "${{ secrets.GCP_PROJECT_ID }}" || ((MISSING_SECRETS++))
        check_secret "GCP_REGION" "${{ secrets.GCP_REGION }}" || ((MISSING_SECRETS++))
        check_secret "GCP_SA_KEY" "${{ secrets.GCP_SA_KEY }}" || ((MISSING_SECRETS++))
        
        echo ""
        echo "2️⃣ Database Secrets:"
        check_secret "DATABASE_URL" "${{ secrets.DATABASE_URL }}" || ((MISSING_SECRETS++))
        check_secret "SUPABASE_URL" "${{ secrets.SUPABASE_URL }}" || ((MISSING_SECRETS++))
        check_secret "SUPABASE_ANON_KEY" "${{ secrets.SUPABASE_ANON_KEY }}" || ((MISSING_SECRETS++))
        check_secret "SUPABASE_SERVICE_KEY" "${{ secrets.SUPABASE_SERVICE_KEY }}" || ((MISSING_SECRETS++))
        
        echo ""
        echo "3️⃣ API Keys:"
        check_secret "OPENAI_API_KEY" "${{ secrets.OPENAI_API_KEY }}" || ((MISSING_SECRETS++))
        check_secret "ANTHROPIC_API_KEY" "${{ secrets.ANTHROPIC_API_KEY }}" || ((MISSING_SECRETS++))
        check_secret "SERPER_API_KEY" "${{ secrets.SERPER_API_KEY }}" || ((MISSING_SECRETS++))
        
        echo ""
        echo "4️⃣ Other Services:"
        check_secret "REDIS_URL" "${{ secrets.REDIS_URL }}" || ((MISSING_SECRETS++))
        check_secret "RESEND_API_KEY" "${{ secrets.RESEND_API_KEY }}" || ((MISSING_SECRETS++))
        check_secret "JWT_SECRET_KEY" "${{ secrets.JWT_SECRET_KEY }}" || ((MISSING_SECRETS++))
        check_secret "SENTRY_DSN" "${{ secrets.SENTRY_DSN }}" || ((MISSING_SECRETS++))
        
        echo ""
        echo "5️⃣ Deployment Secrets:"
        check_secret "VERCEL_TOKEN" "${{ secrets.VERCEL_TOKEN }}" || ((MISSING_SECRETS++))
        check_secret "VERCEL_ORG_ID" "${{ secrets.VERCEL_ORG_ID }}" || ((MISSING_SECRETS++))
        check_secret "VERCEL_PROJECT_ID" "${{ secrets.VERCEL_PROJECT_ID }}" || ((MISSING_SECRETS++))
        check_secret "NEXT_PUBLIC_API_URL" "${{ secrets.NEXT_PUBLIC_API_URL }}" || ((MISSING_SECRETS++))
        
        echo ""
        echo "6️⃣ Optional Secrets:"
        check_secret "SLACK_WEBHOOK_URL" "${{ secrets.SLACK_WEBHOOK_URL }}" || echo "  (Optional - for notifications)"
        
        echo ""
        echo "======================================"
        if [ $MISSING_SECRETS -eq 0 ]; then
          echo "✅ All required secrets are configured!"
        else
          echo "❌ Missing $MISSING_SECRETS required secrets"
          echo ""
          echo "To add missing secrets:"
          echo "1. Go to: https://github.com/${{ github.repository }}/settings/secrets/actions"
          echo "2. Click 'New repository secret'"
          echo "3. Add each missing secret"
          exit 1
        fi
    
    - name: Test GCP Authentication
      uses: google-github-actions/auth@v2
      continue-on-error: true
      id: auth
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Check GCP Auth Result
      if: steps.auth.outcome == 'success'
      run: |
        echo "✅ GCP Authentication successful!"
        echo "Project: ${{ secrets.GCP_PROJECT_ID }}"
    
    - name: Check GCP Auth Error
      if: steps.auth.outcome == 'failure'
      run: |
        echo "❌ GCP Authentication failed!"
        echo "Please check your GCP_SA_KEY secret"
        echo "Make sure it contains valid service account JSON"
    
    - name: Summary
      if: always()
      run: |
        echo ""
        echo "📋 Configuration Summary"
        echo "======================="
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Workflow: ${{ github.workflow }}"
        echo ""
        echo "Next steps:"
        echo "1. Add any missing secrets at:"
        echo "   https://github.com/${{ github.repository }}/settings/secrets/actions"
        echo "2. Re-run this workflow to verify"
        echo "3. Once all secrets are set, deployment should work!"